services:
  web:
    image: nginx:alpine
    ports:
      - "10001:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    tmpfs:
      - /var/cache/nginx:size=100M,mode=0755
      - /tmp:size=50M,mode=1777
    restart: unless-stopped
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=2048
    command: ["sh", "-c", "nginx -t && nginx -g 'daemon off;'"]
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M